(function attachChromeFactCheckLocalization(globalScope) {
  const DEFAULT_LOCALE = "en-US";
  const SUPPORTED_LOCALES = Object.freeze(["en-US", "sv-SE", "de-DE", "fr-FR", "es-ES"]);

    const STRINGS = Object.freeze({
      "en-US": Object.freeze({
        "lang.auto": "Auto (page/browser locale)",
        "lang.en-US": "English",
        "lang.sv-SE": "Swedish",
        "lang.de-DE": "German",
        "lang.fr-FR": "French",
        "lang.es-ES": "Spanish",
        "menu.selection": "Fact-check selected text",
        "ui.readMore": "Read more...",
        "ui.settings": "Settings",
        "ui.none": "None",
        "prob.true": "True",
        "prob.false": "False",
        "verdict.SUPPORTED": "SUPPORTED",
        "verdict.DISPUTED": "DISPUTED",
        "verdict.MISLEADING": "MISLEADING",
        "verdict.UNCLEAR": "UNCLEAR",
        "action.idle": "Chrome Fact Check",
        "action.thinking": "Chrome Fact Check: thinking...",
        "action.success": "Chrome Fact Check: latest check completed",
        "action.error": "Chrome Fact Check: latest check failed",
        "fact.noSelection": "No text was selected. Highlight text and try again.",
        "fact.failedTitle": "Fact-check failed",
        "fact.thinkingTitle": "Fact-checking...",
        "fact.thinkingSummary": "Checking the selected text and linked sources now. This can take a few seconds.",
        "fact.summaryTitle": "Fact-check summary",
        "fact.spinnerInProgress": "Fact-check in progress",
        "fact.popoverNoSummary": "No summary available.",
        "fact.popoverCloseSummaryAria": "Close fact-check summary",
        "fact.quickPromptTitle": "Fact-check this selection?",
        "fact.quickPromptCloseAria": "Close fact-check prompt",
        "fact.quickPromptAction": "Fact-check",
        "fact.quickPromptStarting": "Starting...",
        "fact.probabilityLine": "Estimated probability: true {truePct}% and false {falsePct}%",
        "fact.primaryClaimLine": "Primary claim: {verdict} ({confidence}%)",
        "fact.sourcesLineWithFailed": "Checked sources: {fetchedCount} fetched, {failedCount} failed",
        "fact.sourcesLineFetchedOnly": "Checked sources: {fetchedCount} fetched",
        "fact.noSourcesLine": "No links were included in the selected text",
        "fact.openDetailsLine": "Open Read more for claim-by-claim detail",
        "err.setBackendUrl": "Set Backend URL in extension options.",
        "err.setApiKey": "Set API key in extension options for this provider.",
        "err.setAzureEndpoint": "Set Azure endpoint in extension options.",
        "err.setCustomEndpoint": "Set custom endpoint in extension options.",
        "err.backendNonJson": "Backend returned non-JSON content.",
        "err.unknown": "Unknown error",
        "options.documentTitle": "Chrome Fact Check Settings",
        "options.mainTitle": "Chrome Fact Check Settings",
        "options.sectionBackend": "Backend",
        "options.backendUrlLabel": "Backend URL",
        "options.sectionProvider": "Provider",
        "options.providerLabel": "Provider",
        "options.providerOpenAi": "OpenAI",
        "options.providerAzureOpenAi": "Azure OpenAI",
        "options.providerCustom": "Custom (OpenAI-compatible)",
        "options.apiKeyLabel": "API Key",
        "options.apiKeyHelp": "Stored locally in browser storage.",
        "options.endpointLabel": "Endpoint (optional for OpenAI)",
        "options.modelLabel": "Model",
        "options.sectionBehavior": "Fact-check behavior",
        "options.strictnessLabel": "Strictness",
        "options.strictnessLow": "Low",
        "options.strictnessMedium": "Medium",
        "options.strictnessHigh": "High",
        "options.answerLanguageLabel": "Answer language",
        "options.maxSourcesLabel": "Max Sources",
        "options.includePageUrlLabel": "Include page URL in requests",
        "options.sectionDomainControls": "Domain controls",
        "options.trustedDomainsLabel": "Trusted domains (comma or newline separated)",
        "options.blockedDomainsLabel": "Blocked domains (comma or newline separated)",
        "options.saveButton": "Save settings",
        "options.statusLoadFailed": "Failed to load settings.",
        "options.statusSaved": "Settings saved.",
        "options.statusMaxSourcesRange": "Max Sources must be between 3 and 8.",
        "options.placeholderBackendUrl": "https://chromefactcheck-api.azurewebsites.net",
        "options.placeholderEndpoint": "https://api.openai.com",
        "options.placeholderModel": "gpt-4.1-mini",
        "options.placeholderTrustedDomains": "wikipedia.org\nwho.int\nscb.se",
        "popup.documentTitle": "Chrome Fact Check",
        "popup.mainTitle": "Chrome Fact Check",
        "popup.subtitle": "Quick controls",
        "popup.answerLanguageLabel": "Answer language",
        "popup.openSettings": "Open settings",
        "popup.openResult": "Open latest report",
        "popup.statusLoadFailed": "Failed to load settings.",
        "popup.statusLanguageSaved": "Language saved.",
        "result.documentTitle": "Fact-check result",
        "result.mainTitle": "Fact-check result",
        "result.loadingText": "Loading full report...",
        "result.requestFailedTitle": "Request failed",
        "result.errorHint": "Open extension settings and verify backend URL, provider endpoint, model, and API key.",
        "result.openSettings": "Open settings",
        "result.selectedTextTitle": "Selected text",
        "result.overallAssessmentTitle": "Overall assessment",
        "result.keyRisksTitle": "Key risks",
        "result.whatToCheckNextTitle": "What to check next",
        "result.checkedSourcesTitle": "Checked sources",
        "result.claimsTitle": "Claims",
        "result.emptyPrefix": "No fact-check result found yet. Select text on a webpage, then choose",
        "result.emptySuffix": "from the context menu.",
        "result.timestampUpdated": "Updated {timestamp}",
        "result.timestampNone": "No runs yet",
        "result.errorLoadFailed": "Failed to load result.",
        "result.summaryNone": "No summary returned.",
        "result.sourcesNone": "No source links were included in the selected text.",
        "result.untitledSource": "(untitled source)",
        "result.sourceStatusUnknown": "unknown",
        "result.sourceStatusLine": "{status} - {url}",
        "result.noClaims": "No claims returned.",
        "result.emptyClaim": "(empty claim)",
        "result.noExplanation": "No explanation returned.",
        "result.searchQueriesTitle": "Search queries",
        "result.evidenceNeededTitle": "Evidence needed",
        "result.probabilityLine": "True: {truePct}% | False: {falsePct}%",
        "result.confidenceLine": "Confidence: {confidence}%",
      }),
      "sv-SE": Object.freeze({
        "lang.auto": "Auto (sidans/webbläsarens språk)",
        "lang.en-US": "Engelska",
        "lang.sv-SE": "Svenska",
        "lang.de-DE": "Tyska",
        "lang.fr-FR": "Franska",
        "lang.es-ES": "Spanska",
        "menu.selection": "Faktakolla markerad text",
        "ui.readMore": "Läs mer...",
        "ui.settings": "Inställningar",
        "ui.none": "Ingen",
        "prob.true": "Sant",
        "prob.false": "Falskt",
        "verdict.SUPPORTED": "STÖD",
        "verdict.DISPUTED": "OMTRIST",
        "verdict.MISLEADING": "MISVISANDE",
        "verdict.UNCLEAR": "OKLAR",
        "action.idle": "Chrome Faktakontroll",
        "action.thinking": "Chrome Faktacheck: tänker...",
        "action.success": "Chrome Faktakontroll: senaste kontrollen slutförd",
        "action.error": "Chrome Faktakontroll: senaste kontrollen misslyckades",
        "fact.noSelection": "Ingen text har valts. Markera text och försök igen.",
        "fact.failedTitle": "Faktakoll misslyckades",
        "fact.thinkingTitle": "Faktakollar...",
        "fact.thinkingSummary": "Kontrollerar vald text och länkade källor nu. Detta kan ta några sekunder.",
        "fact.summaryTitle": "Faktakoll sammanfattning",
        "fact.spinnerInProgress": "Faktakontroll pågår",
        "fact.popoverNoSummary": "Ingen sammanfattning tillgänglig.",
        "fact.popoverCloseSummaryAria": "Stäng faktakontrollsammanfattning",
        "fact.quickPromptTitle": "Faktakolla detta urval?",
        "fact.quickPromptCloseAria": "Stäng faktakontrollprompt",
        "fact.quickPromptAction": "Faktakoll",
        "fact.quickPromptStarting": "Startande...",
        "fact.probabilityLine": "Uppskattad sannolikhet: sant {truePct}% och falskt {falsePct}%",
        "fact.primaryClaimLine": "Primärt anspråk: {verdict} ({confidence}%)",
        "fact.sourcesLineWithFailed": "Markerade källor: {fetchedCount} hämtade, {failedCount} misslyckades",
        "fact.sourcesLineFetchedOnly": "Markerade källor: {fetchedCount} hämtade",
        "fact.noSourcesLine": "Inga länkar inkluderades i den valda texten",
        "fact.openDetailsLine": "Öppna Läs mer för anspråk-för-krav-detaljer",
        "err.setBackendUrl": "Ställ in Backend-URL i tilläggsalternativ.",
        "err.setApiKey": "Ställ in API-nyckel i tilläggsalternativ för den här leverantören.",
        "err.setAzureEndpoint": "Ställ in Azure-slutpunkt i tilläggsalternativ.",
        "err.setCustomEndpoint": "Ställ in anpassad slutpunkt i tilläggsalternativ.",
        "err.backendNonJson": "Backend returnerade icke-JSON-innehåll.",
        "err.unknown": "Okänt fel",
        "options.documentTitle": "Chrome Faktakontrollinställningar",
        "options.mainTitle": "Chrome Faktakontrollinställningar",
        "options.sectionBackend": "Backend",
        "options.backendUrlLabel": "Backend-URL",
        "options.sectionProvider": "Leverantör",
        "options.providerLabel": "Leverantör",
        "options.providerOpenAi": "OpenAI",
        "options.providerAzureOpenAi": "Azure OpenAI",
        "options.providerCustom": "Anpassad (OpenAI-kompatibel)",
        "options.apiKeyLabel": "API-nyckel",
        "options.apiKeyHelp": "Lagras lokalt i webbläsarens lagring.",
        "options.endpointLabel": "Slutpunkt (valfritt för OpenAI)",
        "options.modelLabel": "Modell",
        "options.sectionBehavior": "Faktakontrollbeteende",
        "options.strictnessLabel": "Strikthet",
        "options.strictnessLow": "Låg",
        "options.strictnessMedium": "Medium",
        "options.strictnessHigh": "Hög",
        "options.answerLanguageLabel": "Svarsspråk",
        "options.maxSourcesLabel": "Max källor",
        "options.includePageUrlLabel": "Inkludera sidans URL i förfrågningar",
        "options.sectionDomainControls": "Domänkontroller",
        "options.trustedDomainsLabel": "Betrodda domäner (komma eller nyradseparerade)",
        "options.blockedDomainsLabel": "Blockerade domäner (komma eller nyradseparerade)",
        "options.saveButton": "Spara inställningar",
        "options.statusLoadFailed": "Det gick inte att läsa in inställningarna.",
        "options.statusSaved": "Inställningar sparade.",
        "options.statusMaxSourcesRange": "Max. källor måste vara mellan 3 och 8.",
        "options.placeholderBackendUrl": "https://chromefactcheck-api.azurewebsites.net",
        "options.placeholderEndpoint": "https://api.openai.com",
        "options.placeholderModel": "gpt-4.1-mini",
        "options.placeholderTrustedDomains": "wikipedia.org\nvem.int\nscb.se",
        "popup.documentTitle": "Chrome Faktakontroll",
        "popup.mainTitle": "Chrome Faktakontroll",
        "popup.subtitle": "Snabba kontroller",
        "popup.answerLanguageLabel": "Svarsspråk",
        "popup.openSettings": "Öppna inställningar",
        "popup.openResult": "Öppna senaste rapporten",
        "popup.statusLoadFailed": "Det gick inte att läsa in inställningarna.",
        "popup.statusLanguageSaved": "Språket har sparats.",
        "result.documentTitle": "Resultat av faktakontroll",
        "result.mainTitle": "Resultat av faktakontroll",
        "result.loadingText": "Laddar hela rapporten...",
        "result.requestFailedTitle": "Begäran misslyckades",
        "result.errorHint": "Öppna tilläggsinställningar och verifiera backend-URL, leverantörsslutpunkt, modell och API-nyckel.",
        "result.openSettings": "Öppna inställningar",
        "result.selectedTextTitle": "Markerad text",
        "result.overallAssessmentTitle": "Helhetsbedömning",
        "result.keyRisksTitle": "Viktiga risker",
        "result.whatToCheckNextTitle": "Vad du ska kolla härnäst",
        "result.checkedSourcesTitle": "Kontrollerade källor",
        "result.claimsTitle": "Anspråk",
        "result.emptyPrefix": "Inget resultat för faktakontroll har hittats ännu. Markera text på en webbsida och välj sedan",
        "result.emptySuffix": "från snabbmenyn.",
        "result.timestampUpdated": "Uppdaterad {timestamp}",
        "result.timestampNone": "Inga löpningar än",
        "result.errorLoadFailed": "Det gick inte att läsa in resultatet.",
        "result.summaryNone": "Ingen sammanfattning returnerades.",
        "result.sourcesNone": "Inga källlänkar inkluderades i den valda texten.",
        "result.untitledSource": "(namnlös källa)",
        "result.sourceStatusUnknown": "okänd",
        "result.sourceStatusLine": "{status} - {url}",
        "result.noClaims": "Inga reklamationer returnerades.",
        "result.emptyClaim": "(tomt anspråk)",
        "result.noExplanation": "Ingen förklaring återkom.",
        "result.searchQueriesTitle": "Sökfrågor",
        "result.evidenceNeededTitle": "Bevis behövs",
        "result.probabilityLine": "Sant: {truePct}% | Falskt: {falsePct}%",
        "result.confidenceLine": "Förtroende: {confidence}%",
      }),
      "de-DE": Object.freeze({
        "lang.auto": "Auto (Seiten-/Browser-Sprache)",
        "lang.en-US": "Englisch",
        "lang.sv-SE": "Schwedisch",
        "lang.de-DE": "Deutsch",
        "lang.fr-FR": "Französisch",
        "lang.es-ES": "Spanisch",
        "menu.selection": "Markierten Text prüfen",
        "ui.readMore": "Mehr lesen...",
        "ui.settings": "Einstellungen",
        "ui.none": "Keiner",
        "prob.true": "Wahr",
        "prob.false": "Falsch",
        "verdict.SUPPORTED": "UNTERSTÜTZT",
        "verdict.DISPUTED": "UMSTRITTEN",
        "verdict.MISLEADING": "IRREFÜHREND",
        "verdict.UNCLEAR": "UNKLAR",
        "action.idle": "Chrome-Faktencheck",
        "action.thinking": "Chrome-Faktencheck: Denken ...",
        "action.success": "Chrome-Faktencheck: Letzter Check abgeschlossen",
        "action.error": "Chrome-Faktencheck: Die letzte Überprüfung ist fehlgeschlagen",
        "fact.noSelection": "Es wurde kein Text ausgewählt. Markieren Sie den Text und versuchen Sie es erneut.",
        "fact.failedTitle": "Faktencheck fehlgeschlagen",
        "fact.thinkingTitle": "Faktencheck läuft...",
        "fact.thinkingSummary": "Überprüfen Sie jetzt den ausgewählten Text und die verknüpften Quellen. Dies kann einige Sekunden dauern.",
        "fact.summaryTitle": "Faktencheck Zusammenfassung",
        "fact.spinnerInProgress": "Faktencheck läuft",
        "fact.popoverNoSummary": "Keine Zusammenfassung verfügbar.",
        "fact.popoverCloseSummaryAria": "Zusammenfassung des Faktenchecks abschließen",
        "fact.quickPromptTitle": "Diese Auswahl auf Fakten überprüfen?",
        "fact.quickPromptCloseAria": "Schließen Sie die Eingabeaufforderung zur Faktenprüfung",
        "fact.quickPromptAction": "Faktencheck",
        "fact.quickPromptStarting": "Beginnt...",
        "fact.probabilityLine": "Geschätzte Wahrscheinlichkeit: wahr {truePct} % und falsch {falsePct} %",
        "fact.primaryClaimLine": "Hauptanspruch: {verdict} ({confidence}%)",
        "fact.sourcesLineWithFailed": "Überprüfte Quellen: {fetchedCount} abgerufen, {failedCount} fehlgeschlagen",
        "fact.sourcesLineFetchedOnly": "Überprüfte Quellen: {fetchedCount} abgerufen",
        "fact.noSourcesLine": "Im ausgewählten Text waren keine Links enthalten",
        "fact.openDetailsLine": "Öffnen Sie „Lesen Sie mehr“, um Einzelheiten zu den einzelnen Ansprüchen zu erfahren",
        "err.setBackendUrl": "Legen Sie die Backend-URL in den Erweiterungsoptionen fest.",
        "err.setApiKey": "Legen Sie den API-Schlüssel in den Erweiterungsoptionen für diesen Anbieter fest.",
        "err.setAzureEndpoint": "Legen Sie den Azure-Endpunkt in den Erweiterungsoptionen fest.",
        "err.setCustomEndpoint": "Legen Sie in den Erweiterungsoptionen einen benutzerdefinierten Endpunkt fest.",
        "err.backendNonJson": "Das Backend hat Nicht-JSON-Inhalte zurückgegeben.",
        "err.unknown": "Unbekannter Fehler",
        "options.documentTitle": "Chrome-Faktencheck-Einstellungen",
        "options.mainTitle": "Chrome-Faktencheck-Einstellungen",
        "options.sectionBackend": "Backend",
        "options.backendUrlLabel": "Backend-URL",
        "options.sectionProvider": "Anbieter",
        "options.providerLabel": "Anbieter",
        "options.providerOpenAi": "OpenAI",
        "options.providerAzureOpenAi": "Azure OpenAI",
        "options.providerCustom": "Benutzerdefiniert (OpenAI-kompatibel)",
        "options.apiKeyLabel": "API-Schlüssel",
        "options.apiKeyHelp": "Lokal im Browserspeicher gespeichert.",
        "options.endpointLabel": "Endpunkt (optional für OpenAI)",
        "options.modelLabel": "Modell",
        "options.sectionBehavior": "Verhalten im Faktencheck",
        "options.strictnessLabel": "Strenge",
        "options.strictnessLow": "Niedrig",
        "options.strictnessMedium": "Medium",
        "options.strictnessHigh": "Hoch",
        "options.answerLanguageLabel": "Antwortsprache",
        "options.maxSourcesLabel": "Max-Quellen",
        "options.includePageUrlLabel": "Fügen Sie die Seiten-URL in Anfragen ein",
        "options.sectionDomainControls": "Domänenkontrollen",
        "options.trustedDomainsLabel": "Vertrauenswürdige Domänen (durch Komma oder Zeilenumbruch getrennt)",
        "options.blockedDomainsLabel": "Blockierte Domänen (durch Komma oder Zeilenumbruch getrennt)",
        "options.saveButton": "Einstellungen speichern",
        "options.statusLoadFailed": "Die Einstellungen konnten nicht geladen werden.",
        "options.statusSaved": "Einstellungen gespeichert.",
        "options.statusMaxSourcesRange": "Die maximalen Quellen müssen zwischen 3 und 8 liegen.",
        "options.placeholderBackendUrl": "https://chromefactcheck-api.azurewebsites.net",
        "options.placeholderEndpoint": "https://api.openai.com",
        "options.placeholderModel": "gpt-4.1-mini",
        "options.placeholderTrustedDomains": "wikipedia.org\nwho.int\nscb.se",
        "popup.documentTitle": "Chrome-Faktencheck",
        "popup.mainTitle": "Chrome-Faktencheck",
        "popup.subtitle": "Schnelle Kontrollen",
        "popup.answerLanguageLabel": "Antwortsprache",
        "popup.openSettings": "Einstellungen öffnen",
        "popup.openResult": "Aktuellen Bericht öffnen",
        "popup.statusLoadFailed": "Die Einstellungen konnten nicht geladen werden.",
        "popup.statusLanguageSaved": "Sprache gespeichert.",
        "result.documentTitle": "Ergebnis des Faktenchecks",
        "result.mainTitle": "Ergebnis des Faktenchecks",
        "result.loadingText": "Vollständiger Bericht wird geladen...",
        "result.requestFailedTitle": "Die Anfrage ist fehlgeschlagen",
        "result.errorHint": "Öffnen Sie die Erweiterungseinstellungen und überprüfen Sie die Backend-URL, den Anbieterendpunkt, das Modell und den API-Schlüssel.",
        "result.openSettings": "Einstellungen öffnen",
        "result.selectedTextTitle": "Ausgewählter Text",
        "result.overallAssessmentTitle": "Gesamtbewertung",
        "result.keyRisksTitle": "Hauptrisiken",
        "result.whatToCheckNextTitle": "Was als nächstes zu überprüfen ist",
        "result.checkedSourcesTitle": "Überprüfte Quellen",
        "result.claimsTitle": "Ansprüche",
        "result.emptyPrefix": "Noch kein Ergebnis des Faktenchecks gefunden. Wählen Sie Text auf einer Webseite aus und wählen Sie dann",
        "result.emptySuffix": "aus dem Kontextmenü.",
        "result.timestampUpdated": "Aktualisiert {timestamp}",
        "result.timestampNone": "Noch keine Läufe",
        "result.errorLoadFailed": "Ergebnis konnte nicht geladen werden.",
        "result.summaryNone": "Es wurde keine Zusammenfassung zurückgegeben.",
        "result.sourcesNone": "Im ausgewählten Text waren keine Quelllinks enthalten.",
        "result.untitledSource": "(Quelle ohne Titel)",
        "result.sourceStatusUnknown": "unbekannt",
        "result.sourceStatusLine": "{status} - {url}",
        "result.noClaims": "Es wurden keine Reklamationen zurückgegeben.",
        "result.emptyClaim": "(leerer Anspruch)",
        "result.noExplanation": "Es wurde keine Erklärung zurückgegeben.",
        "result.searchQueriesTitle": "Suchanfragen",
        "result.evidenceNeededTitle": "Beweise erforderlich",
        "result.probabilityLine": "Wahr: {truePct}% | Falsch: {falsePct}%",
        "result.confidenceLine": "Vertrauen: {confidence}%",
      }),
      "fr-FR": Object.freeze({
        "lang.auto": "Auto (langue page/navigateur)",
        "lang.en-US": "Anglais",
        "lang.sv-SE": "Suédois",
        "lang.de-DE": "Allemand",
        "lang.fr-FR": "Français",
        "lang.es-ES": "Espagnol",
        "menu.selection": "Vérifier le texte sélectionné",
        "ui.readMore": "Lire plus...",
        "ui.settings": "Paramètres",
        "ui.none": "Aucun",
        "prob.true": "Vrai",
        "prob.false": "Faux",
        "verdict.SUPPORTED": "SOUTENU",
        "verdict.DISPUTED": "CONTESTÉ",
        "verdict.MISLEADING": "TROMPEUR",
        "verdict.UNCLEAR": "PEU CLAIR",
        "action.idle": "Vérification des faits sur Chrome",
        "action.thinking": "Chrome Fact Check : réfléchir...",
        "action.success": "Chrome Fact Check : dernière vérification terminée",
        "action.error": "Chrome Fact Check : la dernière vérification a échoué",
        "fact.noSelection": "Aucun texte n'a été sélectionné. Mettez le texte en surbrillance et réessayez.",
        "fact.failedTitle": "Vérification échouée",
        "fact.thinkingTitle": "Vérification en cours...",
        "fact.thinkingSummary": "Vérification du texte sélectionné et des sources liées maintenant. Cela peut prendre quelques secondes.",
        "fact.summaryTitle": "Résumé de vérification",
        "fact.spinnerInProgress": "Vérification des faits en cours",
        "fact.popoverNoSummary": "Aucun résumé disponible.",
        "fact.popoverCloseSummaryAria": "Fermer le résumé de la vérification des faits",
        "fact.quickPromptTitle": "Vérifier cette sélection ?",
        "fact.quickPromptCloseAria": "Fermer l'invite de vérification des faits",
        "fact.quickPromptAction": "Vérification des faits",
        "fact.quickPromptStarting": "Départ...",
        "fact.probabilityLine": "Probabilité estimée : vrai {truePct} % et faux {falsePct} %",
        "fact.primaryClaimLine": "Demande principale : {verdict} ({confidence} %)",
        "fact.sourcesLineWithFailed": "Sources vérifiées : {fetchedCount} récupéré, {failedCount} a échoué",
        "fact.sourcesLineFetchedOnly": "Sources vérifiées : {fetchedCount} récupérées",
        "fact.noSourcesLine": "Aucun lien n'a été inclus dans le texte sélectionné",
        "fact.openDetailsLine": "Ouvrir En savoir plus pour obtenir des détails sur chaque réclamation",
        "err.setBackendUrl": "Définissez l’URL du backend dans les options d’extension.",
        "err.setApiKey": "Définissez la clé API dans les options d'extension pour ce fournisseur.",
        "err.setAzureEndpoint": "Définissez le point de terminaison Azure dans les options d’extension.",
        "err.setCustomEndpoint": "Définissez un point de terminaison personnalisé dans les options d’extension.",
        "err.backendNonJson": "Le backend a renvoyé du contenu non JSON.",
        "err.unknown": "Erreur inconnue",
        "options.documentTitle": "Paramètres de vérification des faits de Chrome",
        "options.mainTitle": "Paramètres de vérification des faits de Chrome",
        "options.sectionBackend": "Back-end",
        "options.backendUrlLabel": "URL du serveur principal",
        "options.sectionProvider": "Fournisseur",
        "options.providerLabel": "Fournisseur",
        "options.providerOpenAi": "OpenAI",
        "options.providerAzureOpenAi": "Azure OpenAI",
        "options.providerCustom": "Personnalisé (compatible OpenAI)",
        "options.apiKeyLabel": "Clé API",
        "options.apiKeyHelp": "Stocké localement dans le stockage du navigateur.",
        "options.endpointLabel": "Point de terminaison (facultatif pour OpenAI)",
        "options.modelLabel": "Modèle",
        "options.sectionBehavior": "Comportement de vérification des faits",
        "options.strictnessLabel": "Rigueur",
        "options.strictnessLow": "Faible",
        "options.strictnessMedium": "Moyen",
        "options.strictnessHigh": "Haut",
        "options.answerLanguageLabel": "Langue de réponse",
        "options.maxSourcesLabel": "Sources maximales",
        "options.includePageUrlLabel": "Inclure l'URL de la page dans les demandes",
        "options.sectionDomainControls": "Contrôles de domaine",
        "options.trustedDomainsLabel": "Domaines de confiance (séparés par des virgules ou des sauts de ligne)",
        "options.blockedDomainsLabel": "Domaines bloqués (séparés par des virgules ou des sauts de ligne)",
        "options.saveButton": "Enregistrer les paramètres",
        "options.statusLoadFailed": "Échec du chargement des paramètres.",
        "options.statusSaved": "Paramètres enregistrés.",
        "options.statusMaxSourcesRange": "Le nombre maximum de sources doit être compris entre 3 et 8.",
        "options.placeholderBackendUrl": "https://chromefactcheck-api.azurewebsites.net",
        "options.placeholderEndpoint": "https://api.openai.com",
        "options.placeholderModel": "gpt-4.1-mini",
        "options.placeholderTrustedDomains": "wikipédia.org\nqui.int\nscb.se",
        "popup.documentTitle": "Vérification des faits sur Chrome",
        "popup.mainTitle": "Vérification des faits sur Chrome",
        "popup.subtitle": "Contrôles rapides",
        "popup.answerLanguageLabel": "Langue de réponse",
        "popup.openSettings": "Ouvrir les paramètres",
        "popup.openResult": "Ouvrir le dernier rapport",
        "popup.statusLoadFailed": "Échec du chargement des paramètres.",
        "popup.statusLanguageSaved": "Langue enregistrée.",
        "result.documentTitle": "Résultat de la vérification des faits",
        "result.mainTitle": "Résultat de la vérification des faits",
        "result.loadingText": "Chargement du rapport complet...",
        "result.requestFailedTitle": "La demande a échoué",
        "result.errorHint": "Ouvrez les paramètres de l'extension et vérifiez l'URL du backend, le point de terminaison du fournisseur, le modèle et la clé API.",
        "result.openSettings": "Ouvrir les paramètres",
        "result.selectedTextTitle": "Texte sélectionné",
        "result.overallAssessmentTitle": "Évaluation globale",
        "result.keyRisksTitle": "Principaux risques",
        "result.whatToCheckNextTitle": "Que vérifier ensuite",
        "result.checkedSourcesTitle": "Sources vérifiées",
        "result.claimsTitle": "Réclamations",
        "result.emptyPrefix": "Aucun résultat de vérification des faits n’a encore été trouvé. Sélectionnez du texte sur une page Web, puis choisissez",
        "result.emptySuffix": "dans le menu contextuel.",
        "result.timestampUpdated": "{timestamp} mis à jour",
        "result.timestampNone": "Aucune course pour l'instant",
        "result.errorLoadFailed": "Échec du chargement du résultat.",
        "result.summaryNone": "Aucun résumé n'a été renvoyé.",
        "result.sourcesNone": "Aucun lien source n'a été inclus dans le texte sélectionné.",
        "result.untitledSource": "(source sans titre)",
        "result.sourceStatusUnknown": "inconnu",
        "result.sourceStatusLine": "{status} - {url}",
        "result.noClaims": "Aucune réclamation n'a été renvoyée.",
        "result.emptyClaim": "(réclamation vide)",
        "result.noExplanation": "Aucune explication n'a été renvoyée.",
        "result.searchQueriesTitle": "Requêtes de recherche",
        "result.evidenceNeededTitle": "Preuves nécessaires",
        "result.probabilityLine": "Vrai : {truePct}% | Faux : {falsePct} %",
        "result.confidenceLine": "Confiance : {confidence} %",
      }),
      "es-ES": Object.freeze({
        "lang.auto": "Auto (idioma de página/navegador)",
        "lang.en-US": "Inglés",
        "lang.sv-SE": "Sueco",
        "lang.de-DE": "Alemán",
        "lang.fr-FR": "Francés",
        "lang.es-ES": "Español",
        "menu.selection": "Verificar texto seleccionado",
        "ui.readMore": "Leer más...",
        "ui.settings": "Configuración",
        "ui.none": "Ninguno",
        "prob.true": "Verdadero",
        "prob.false": "Falso",
        "verdict.SUPPORTED": "APOYADO",
        "verdict.DISPUTED": "CUESTIONADO",
        "verdict.MISLEADING": "ENGAÑOSO",
        "verdict.UNCLEAR": "NO CLARO",
        "action.idle": "Verificación de datos de Chrome",
        "action.thinking": "Chrome Fact Check: pensando...",
        "action.success": "Chrome Fact Check: última verificación completada",
        "action.error": "Chrome Fact Check: la última comprobación falló",
        "fact.noSelection": "No se seleccionó ningún texto. Resalta el texto e inténtalo de nuevo.",
        "fact.failedTitle": "Verificación fallida",
        "fact.thinkingTitle": "Verificando...",
        "fact.thinkingSummary": "Comprobando el texto seleccionado y las fuentes vinculadas ahora. Esto puede tardar unos segundos.",
        "fact.summaryTitle": "Resumen de verificación",
        "fact.spinnerInProgress": "Verificación de hechos en progreso",
        "fact.popoverNoSummary": "No hay resumen disponible.",
        "fact.popoverCloseSummaryAria": "Cerrar resumen de verificación de datos",
        "fact.quickPromptTitle": "¿Verificar esta selección?",
        "fact.quickPromptCloseAria": "Cerrar mensaje de verificación de hechos",
        "fact.quickPromptAction": "Verificación de hechos",
        "fact.quickPromptStarting": "A partir de...",
        "fact.probabilityLine": "Probabilidad estimada: verdadero {truePct}% y falso {falsePct}%",
        "fact.primaryClaimLine": "Reclamación principal: {verdict} ({confidence}%)",
        "fact.sourcesLineWithFailed": "Fuentes comprobadas: {fetchedCount} obtenida, {failedCount} fallida",
        "fact.sourcesLineFetchedOnly": "Fuentes comprobadas: {fetchedCount} obtenidas",
        "fact.noSourcesLine": "No se incluyeron enlaces en el texto seleccionado.",
        "fact.openDetailsLine": "Abrir Leer más para obtener detalles reclamo por reclamo",
        "err.setBackendUrl": "Establezca la URL de backend en las opciones de extensión.",
        "err.setApiKey": "Establezca la clave API en las opciones de extensión para este proveedor.",
        "err.setAzureEndpoint": "Configure el punto final de Azure en las opciones de extensión.",
        "err.setCustomEndpoint": "Establezca un punto final personalizado en las opciones de extensión.",
        "err.backendNonJson": "El backend devolvió contenido que no es JSON.",
        "err.unknown": "Error desconocido",
        "options.documentTitle": "Configuración de verificación de datos de Chrome",
        "options.mainTitle": "Configuración de verificación de datos de Chrome",
        "options.sectionBackend": "backend",
        "options.backendUrlLabel": "URL de fondo",
        "options.sectionProvider": "Proveedor",
        "options.providerLabel": "Proveedor",
        "options.providerOpenAi": "Abierto AI",
        "options.providerAzureOpenAi": "Azure abierto AI",
        "options.providerCustom": "Personalizado (compatible con OpenAI)",
        "options.apiKeyLabel": "Clave API",
        "options.apiKeyHelp": "Almacenado localmente en el almacenamiento del navegador.",
        "options.endpointLabel": "Punto final (opcional para OpenAI)",
        "options.modelLabel": "Modelo",
        "options.sectionBehavior": "Comportamiento de verificación de hechos",
        "options.strictnessLabel": "Rigor",
        "options.strictnessLow": "Bajo",
        "options.strictnessMedium": "Medio",
        "options.strictnessHigh": "Alto",
        "options.answerLanguageLabel": "Idioma de respuesta",
        "options.maxSourcesLabel": "Fuentes máximas",
        "options.includePageUrlLabel": "Incluir la URL de la página en las solicitudes",
        "options.sectionDomainControls": "Controles de dominio",
        "options.trustedDomainsLabel": "Dominios confiables (separados por comas o nueva línea)",
        "options.blockedDomainsLabel": "Dominios bloqueados (separados por comas o nueva línea)",
        "options.saveButton": "Guardar configuración",
        "options.statusLoadFailed": "No se pudo cargar la configuración.",
        "options.statusSaved": "Configuración guardada.",
        "options.statusMaxSourcesRange": "Las fuentes máximas deben estar entre 3 y 8.",
        "options.placeholderBackendUrl": "https://chromefactcheck-api.azurewebsites.net",
        "options.placeholderEndpoint": "https://api.openai.com",
        "options.placeholderModel": "gpt-4.1-mini",
        "options.placeholderTrustedDomains": "wikipedia.org\nquien.int\nscb.se",
        "popup.documentTitle": "Verificación de datos de Chrome",
        "popup.mainTitle": "Verificación de datos de Chrome",
        "popup.subtitle": "Controles rápidos",
        "popup.answerLanguageLabel": "Idioma de respuesta",
        "popup.openSettings": "Abrir configuración",
        "popup.openResult": "Abrir el último informe",
        "popup.statusLoadFailed": "No se pudo cargar la configuración.",
        "popup.statusLanguageSaved": "Idioma guardado.",
        "result.documentTitle": "Resultado de la verificación de hechos",
        "result.mainTitle": "Resultado de la verificación de hechos",
        "result.loadingText": "Cargando informe completo...",
        "result.requestFailedTitle": "Solicitud fallida",
        "result.errorHint": "Abra la configuración de la extensión y verifique la URL del backend, el punto final del proveedor, el modelo y la clave API.",
        "result.openSettings": "Abrir configuración",
        "result.selectedTextTitle": "Texto seleccionado",
        "result.overallAssessmentTitle": "Evaluación general",
        "result.keyRisksTitle": "Riesgos clave",
        "result.whatToCheckNextTitle": "Qué comprobar a continuación",
        "result.checkedSourcesTitle": "Fuentes comprobadas",
        "result.claimsTitle": "Reclamos",
        "result.emptyPrefix": "Aún no se ha encontrado ningún resultado de verificación de datos. Seleccione texto en una página web y luego elija",
        "result.emptySuffix": "desde el menú contextual.",
        "result.timestampUpdated": "Actualizado {timestamp}",
        "result.timestampNone": "Aún no hay carreras",
        "result.errorLoadFailed": "No se pudo cargar el resultado.",
        "result.summaryNone": "No se devolvió ningún resumen.",
        "result.sourcesNone": "No se incluyeron enlaces de fuentes en el texto seleccionado.",
        "result.untitledSource": "(fuente sin título)",
        "result.sourceStatusUnknown": "desconocido",
        "result.sourceStatusLine": "{status} - {url}",
        "result.noClaims": "No se devolvieron reclamaciones.",
        "result.emptyClaim": "(reclamo vacío)",
        "result.noExplanation": "No se obtuvo ninguna explicación.",
        "result.searchQueriesTitle": "Consultas de búsqueda",
        "result.evidenceNeededTitle": "Se necesita evidencia",
        "result.probabilityLine": "Verdadero: {truePct}% | Falso: {falsePct}%",
        "result.confidenceLine": "Confianza: {confidence}%",
      }),
    });
  
function normalizeLocale(value) {
    if (typeof value !== "string") {
      return "";
    }

    return value.trim().replace("_", "-");
  }

  function matchSupportedLocale(value) {
    const normalized = normalizeLocale(value);

    if (!normalized) {
      return "";
    }

    const exact = SUPPORTED_LOCALES.find((locale) => locale.toLowerCase() === normalized.toLowerCase());

    if (exact) {
      return exact;
    }

    const base = normalized.split("-")[0]?.toLowerCase();
    return SUPPORTED_LOCALES.find((locale) => locale.split("-")[0].toLowerCase() === base) || "";
  }

  function getBrowserLocale() {
    if (typeof chrome !== "undefined" && chrome.i18n && typeof chrome.i18n.getUILanguage === "function") {
      try {
        return chrome.i18n.getUILanguage();
      } catch {
        return "";
      }
    }

    if (typeof navigator !== "undefined") {
      return navigator.language || "";
    }

    return "";
  }

  function resolveLocale(preferredLocale = "auto", options = {}) {
    const preferred = normalizeLocale(preferredLocale);

    if (preferred && preferred.toLowerCase() !== "auto") {
      return matchSupportedLocale(preferred) || DEFAULT_LOCALE;
    }

    const pageLocale = matchSupportedLocale(options.pageLocale || "");
    if (pageLocale) {
      return pageLocale;
    }

    const browserLocale = matchSupportedLocale(options.browserLocale || getBrowserLocale());
    return browserLocale || DEFAULT_LOCALE;
  }

  function formatTemplate(template, values = {}) {
    return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (full, key) => {
      if (!Object.prototype.hasOwnProperty.call(values, key)) {
        return full;
      }

      return String(values[key]);
    });
  }

  function t(locale, key, values = {}) {
    const resolved = matchSupportedLocale(locale) || DEFAULT_LOCALE;
    const localeStrings = STRINGS[resolved] || {};
    const fallbackStrings = STRINGS[DEFAULT_LOCALE];
    const template = Object.prototype.hasOwnProperty.call(localeStrings, key)
      ? localeStrings[key]
      : fallbackStrings[key];

    if (typeof template !== "string") {
      return key;
    }

    return formatTemplate(template, values);
  }

  function getLanguageOptions(locale) {
    const resolved = resolveLocale(locale, {
      pageLocale: typeof document !== "undefined" ? document.documentElement?.lang || "" : "",
      browserLocale: getBrowserLocale()
    });

    return [
      { value: "auto", label: t(resolved, "lang.auto") },
      { value: "en-US", label: t(resolved, "lang.en-US") },
      { value: "sv-SE", label: t(resolved, "lang.sv-SE") },
      { value: "de-DE", label: t(resolved, "lang.de-DE") },
      { value: "fr-FR", label: t(resolved, "lang.fr-FR") },
      { value: "es-ES", label: t(resolved, "lang.es-ES") }
    ];
  }

  function applyTranslations(root, locale) {
    if (typeof document === "undefined") {
      return;
    }

    const target = root && typeof root.querySelectorAll === "function" ? root : document;
    const resolved = resolveLocale(locale, {
      pageLocale: document.documentElement?.lang || "",
      browserLocale: getBrowserLocale()
    });

    for (const node of target.querySelectorAll("[data-i18n]")) {
      const key = node.getAttribute("data-i18n");

      if (key) {
        node.textContent = t(resolved, key);
      }
    }

    for (const node of target.querySelectorAll("[data-i18n-placeholder]")) {
      const key = node.getAttribute("data-i18n-placeholder");

      if (key && "placeholder" in node) {
        node.placeholder = t(resolved, key);
      }
    }

    for (const node of target.querySelectorAll("[data-i18n-aria-label]")) {
      const key = node.getAttribute("data-i18n-aria-label");

      if (key) {
        node.setAttribute("aria-label", t(resolved, key));
      }
    }
  }

  globalScope.ChromeFactCheckI18n = Object.freeze({
    DEFAULT_LOCALE,
    SUPPORTED_LOCALES,
    resolveLocale,
    t,
    getLanguageOptions,
    applyTranslations
  });
})(globalThis);
